name: Build & Publish ISO Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday Midnight

concurrency: build

jobs:
  build-images:
    name: "Build ISO Images"
    if: github.repository == 'shuritch/nixos'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - pandora

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GH_TOKEN }}"

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Fetch LFS objects
        run: git lfs pull

      - name: Install nix
        uses: cachix/install-nix-action@master
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            experimental-features = nix-command flakes ca-derivations auto-allocate-uids cgroups recursive-nix
            allow-import-from-derivation = false

      - name: Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build ISO Images
        shell: bash
        run: nix build .#images.${{ matrix.image }} -o ${{ matrix.image }} --print-build-logs

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}-iso-image
          path: ${{ matrix.image }}/iso/*.iso

  publish-images:
    name: "Publish ISO Images"
    runs-on: ubuntu-latest
    needs: build-images

    permissions:
      contents: write

    env:
      GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"

    steps:
      - name: Download ISO Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R

      - name: Calculate Checksums
        run: |
          calculate_checksum() {
            sha256sum "$1" | awk '{print $1}'
          }

          iso_files=$(find . -maxdepth 1 -type f -name "*.iso")

          # write checksums
          for file in $iso_files; do
            checksum=$(calculate_checksum "$file")
            echo "$file $checksum" >> checksums.txt
          done

      - name: Get current date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d@%H:%M:%S')" >> "${GITHUB_OUTPUT}"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: "iso-${{ steps.get-date.outputs.date }}"
          tag_name: "iso-${{ steps.get-date.outputs.date }}"
          files: |
            *.iso
          body: |
            ## Weekly Release of `${{ steps.get-date.outputs.date }}`

            Weekly automated ISO releases for my Portable NixOS workstation.
            - [pandora](https://github.com/shuritch/nixos/blob/main/cluster/pandora/default.nix): Minimal & Headless Installation Media
